dialgauge 1.5 quacked
updated to dialgauge 1.5 to prevent
TypeError: Cannot read property 'scaleMin' of undefined
    at
parseParameters (angular-dialgauge.js:476)
and quacked it to prevent console Diarrhea