initialization is required at all times
otherwise we get
TypeError: Cannot use 'in' operator to search for '272127' in null
at Object.getSceneName
(file:///D:/DuckieTV-standalone/js/services/SceneNameResolver.js:28:35)
at getSeasonSearchString
(file:///D:/DuckieTV-standalone/js/controllers/sidepanel/SidepanelSeasonCtrl.js:71:34)
when users opt out of torrenting in settings.